### ISSUE TITLE
When add a new nodetree，bake node will lost?

### ISSUE THREAD

**Issue by chenpaner** [avelgest/baker-node#6]
![lost node](https://github.com/avelgest/baker-node/assets/107256886/5cf5a08f-fd9b-4c19-811d-4b290b96d639)

When I add a new NodeTree or append a new NodeTree in blender 4.1，bake node will lost?
I try it in blender_factory_startup!

**Comment by avelgest** [comment]
Thanks for the issue!
Which specific release version of Blender are you using? I've been able to reproduce the bug in Blender 4.1.0, but not 4.1.1 or other versions.

This seems to be a bug in Blender affecting all nodes derived from ShaderNodeCustomGroup when shader node tree assets are linked or appended. I don't think there's any simple way for the add-on to work around this, but versions 4.1.1 and 4.2 alpha are working correctly for me, so if they fix the problem then no changes should be necessary.

**Comment by chenpaner** [comment]
This error occurred in my blender 4.1.0. I guess it's also a blender bug, because there are other ShaderNodeCustomGroup plugins that also encounter this problem, thank you for your reply !
